### ISSUE TITLE
Improve import mechanism

### ISSUE THREAD

**Issue by philogy** [monero-ecosystem/monero-javascript#32]
Currently when I use the recommended mechanism of doing `require('monero-javascript')` my sensible editor wonders where I'm pulling the suddenly defined classes from. While the code itself works this is quite annoying as it would require me to disable eslint. Furthermore importing everything always is not very efficient. I see that when you import monero-javascript what is actually being done in the background is that a function is called that globally defines all the classes and functions. Could you please use a standard form of module exports? I'd much appreciate it!

**Comment by woodser** [comment]
Ok I'm looking into it.

**Comment by woodser** [comment]
I updated the import mechanism in #33 such that [index.js](https://github.com/monero-ecosystem/monero-javascript/blob/standardize_exports/index.js) exports all modules to a scoped object instead of `this`, e.g.:
```
let monerojs = require("monero-javascript");
let daemon = monerojs.connectToDaemonRpc(...)
let walletRpc = monerojs.connectToWalletRpc(...)
let walletWasm = await monerojs.createWalletWasm(...)
let walletKeys = await monerojs.createWalletKeys(...)
```

[sample code](https://github.com/monero-ecosystem/monero-javascript/tree/standardize_exports#sample-code)

Currently, `require("monero-javascript")` will export all library classes, but one _could_ require library classes individually, e.g. `require("monero-javascript/src/wallet/MoneroWalletWasm")`.

Does that provide what you're looking for, or do you have any suggestions?  Thanks.

**Comment by woodser** [comment]
#33 merged to master and released in v0.4.0.

**Comment by philogy** [comment]
Sorry for the late response, this is exactly what I'm looking for thanks!

**Comment by woodser** [comment]
Glad to hear it.
