### ISSUE TITLE
Offline wallet and View only wallet using Monero Wallet RPC.  

### ISSUE THREAD

**Issue by dethos** [monero-ecosystem/monero-javascript#50]
I was trying to test this library in a scenario very similar to the one described [here](https://github.com/monero-ecosystem/monero-javascript/blob/master/docs/developer_guide/view_only_offline.md), the main difference is that the view only wallet is using the standard `monero-wallet-rpc` binary.

I exported the outputs hex using the `export_outputs` method and created an unsigned transaction using the `transfer` method, getting in both cases an `hex` of the required data. When trying to use this data in the `MoneroWalletFull` offline wallet I get the following:

```
> await this.wallet.importOutputsHex("<outputs_data_hex>");
0
> await this.wallet.signTxs("<unsigned_txset_hex>");
undefined
```

It is very likely that I'm missing some intermediate step, such as getting the transaction hex from the `unsigned_txset`, however I couldn't find any information about it.

Is there any documentation, guide or example available on how to do this?

**Comment by woodser** [comment]
Thank you.  I can recreate the issue and I'm looking into it.

**Comment by dethos** [comment]
@woodser Not sure if it is related, but a similar problem is happening on the `monero-wallet-rpc`: https://github.com/monero-project/monero/issues/6901#issuecomment-777583095

So there is the possibility of the problem residing on the generated `hex`s.

**Comment by dethos** [comment]
Extra note: I'm also experiencing the same issue when dealing with multisig wallets (2/3), the transaction is created using `monero-javascript` and `monero-wallet-rpc` needs to sign and submit to the network.

**Comment by woodser** [comment]
This issue is fixed with https://github.com/monero-project/monero/pull/7321 and monero-javascript 0.5.2 which is built with that PR.

Monero CLI must be rebuilt with the PR for the fix to take effect.

Note the import and export functions were renamed in monero-javascript 0.5.2 and support exporting only the outputs and key images since the last export by default:

* [exportOutputs(all=false)](https://moneroecosystem.org/monero-javascript/MoneroWallet.html#exportOutputs)
* [importOutputs(outputsHex)](https://moneroecosystem.org/monero-javascript/MoneroWallet.html#importOutputs)
* [exportKeyImages(all=false)](https://moneroecosystem.org/monero-javascript/MoneroWallet.html#exportKeyImages)
* [importKeyImages(keyImages)](https://moneroecosystem.org/monero-javascript/MoneroWallet.html#importKeyImages)

**Comment by dethos** [comment]
@woodser thanks, I just tested and the initial issue is solved (the one related to "View-only and offline wallets" flow where one of the sides uses the Monero RPC).

However as I mentioned [here](https://github.com/monero-ecosystem/monero-javascript/issues/50#issuecomment-785069047) there seems to be a similar problem regarding multisig transaction `hex`. To test, on one side I just created a multisig transaction using the RPC and then tried to sign it on the other side using monero-javascript's `wallet.signMultisigTxHex(txhex)`. I got the following error: 
> Error: Failed to parse multisig tx data

**Comment by woodser** [comment]
I'm not able to recreate the issue after [adding a test](https://github.com/monero-ecosystem/monero-javascript/commit/81c7a585af2237faa16685b285bb4c7830a2015b) for multisig compatibility.

Does it work as expected if using monero-wallet-rpc for both multisig participants and using the [monero-wallet-rpc client](https://github.com/monero-ecosystem/monero-javascript/blob/master/docs/developer_guide/creating_wallets.md#rpc-wallet) the same way you're testing the full wallet?

**Comment by woodser** [comment]
Closing this since the original issue is resolved.

There is now a [dedicated test](https://github.com/monero-ecosystem/monero-javascript/blob/a07c29b94a6d6bf30f543ed628ec1419c5c56509/src/test/TestMoneroWalletFull.js#L398) to show multisig compatibility between monero-wallet-rpc and wasm.

Please open a new issue if you continue having a problem with multisig compatibility.
